# Lightweight image just for running Prisma migrations
FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

COPY prisma ./prisma

RUN npx prisma generate

CMD ["npx", "prisma", "migrate", "deploy"]
